### ISSUE TITLE
What happen with the assets folder?

### ISSUE THREAD

**Issue by crlsmtzprds** [xtrinch/sails-pagination-middleware#2]
I implement this middleware, but now I can't access to the assets folder (subfolders and files content), for some reason any route that is not model route show a "Not Found" error.

Even if I create a new controller without a model (just for simple tasks) sails show the same "Not Found" error.

Pagination works perfectly showing totalCount and results , but I can't access any other routes.

An example of working route:
http://127.0.0.1:1337/archivos/anuncios/1537380435_ye2l6uz7o.jpeg
(it work before install and config this middleware)

The console is showing this warn/error message (literally):

> warn: res.notFound() :: When attempting to render error page view, an error occured (sending text instead).  Details:  { ReferenceError: /Library/WebServer/Documents/pantallas/pantallaServerAPI/views/layouts/layout.ejs:30
>    28|         &lt;div class=&quot;navbar-nav flex-row&quot;&gt;
>    29|           &lt;!-- LOGGED-IN NAVIGATION --&gt;
> &gt;&gt; 30|           &lt;% if(me) { %&gt;
>    31|           &lt;a class=&quot;nav-item nav-link ml-2 ml-md-0 mr-2 mr-md-0&quot; href=&quot;/contact&quot;&gt;Help&lt;/a&gt;
>    32|           &lt;!-- Only in desktop nav --&gt;
>    33|           &lt;div class=&quot;nav-item dropdown d-none d-sm-block&quot;&gt;
>
>me is not defined
>    at eval (eval at compile (/Library/WebServer/Documents/pantallas/pantallaServerAPI/node_modules/ejs/lib/ejs.js:549:12), &lt;anonymous&gt;:28:8)
>    at returnedFn (/Library/WebServer/Documents/pantallas/pantallaServerAPI/node_modules/ejs/lib/ejs.js:580:17)
>    at tryHandleCache (/Library/WebServer/Documents/pantallas/pantallaServerAPI/node_modules/ejs/lib/ejs.js:223:34)
>    at Object.exports.renderFile (/Library/WebServer/Documents/pantallas/pantallaServerAPI/node_modules/ejs/lib/ejs.js:437:10)
>    at renderFile (/Library/WebServer/Documents/pantallas/pantallaServerAPI/node_modules/sails/lib/hooks/views/default-view-rendering-fn.js:60:7)
>    at /Library/WebServer/Documents/pantallas/pantallaServerAPI/node_modules/sails/lib/hooks/views/default-view-rendering-fn.js:106:7
>    at tryHandleCache (/Library/WebServer/Documents/pantallas/pantallaServerAPI/node_modules/ejs/lib/ejs.js:228:10)
>    at Object.exports.renderFile (/Library/WebServer/Documents/pantallas/pantallaServerAPI/node_modules/ejs/lib/ejs.js:437:10)
>    at Hook.renderFile (/Library/WebServer/Documents/pantallas/pantallaServerAPI/node_modules/sails/lib/hooks/views/default-view-rendering-fn.js:60:7)
>    at SailsView.wrapper [as engine] (/Library/WebServer/Documents/pantallas/pantallaServerAPI/node_modules/@sailshq/lodash/lib/index.js:3275:19)
>    at SailsView.render (/Library/WebServer/Documents/pantallas/pantallaServerAPI/node_modules/express/lib/view.js:135:8)
>    at tryRender (/Library/WebServer/Documents/pantallas/pantallaServerAPI/node_modules/express/lib/application.js:640:10)
>    at Function.render (/Library/WebServer/Documents/pantallas/pantallaServerAPI/node_modules/express/lib/application.js:592:3)
>    at ServerResponse.render (/Library/WebServer/Documents/pantallas/pantallaServerAPI/node_modules/express/lib/response.js:1008:7)
>    at ServerResponse.res.view (/Library/WebServer/Documents/pantallas/pantallaServerAPI/node_modules/sails/lib/hooks/views/res.view.js:336:16)
>    at Object.notFound (/Library/WebServer/Documents/pantallas/pantallaServerAPI/node_modules/sails/lib/hooks/responses/defaults/notFound.js:45:14)
>    at Sails.404 (/Library/WebServer/Documents/pantallas/pantallaServerAPI/node_modules/sails/lib/router/bindDefaultHandlers.js:102:22)
>    at emitTwo (events.js:126:13)
>    at Sails.emit (events.js:214:7)
>    at Sails.emitter.emit (/Library/WebServer/Documents/pantallas/pantallaServerAPI/node_modules/sails/lib/app/private/after.js:56:26)
>    at handleUnmatchedRequest (/Library/WebServer/Documents/pantallas/pantallaServerAPI/node_modules/sails/lib/hooks/http/initialize.js:416:19)
>    at Layer.handle [as handle_request] (/Library/WebServer/Documents/pantallas/pantallaServerAPI/node_modules/express/lib/router/layer.js:95:5)
>    at trim_prefix (/Library/WebServer/Documents/pantallas/pantallaServerAPI/node_modules/express/lib/router/index.js:317:13)
>    at /Library/WebServer/Documents/pantallas/pantallaServerAPI/node_modules/express/lib/router/index.js:284:7
>    at Function.process_params (/Library/WebServer/Documents/pantallas/pantallaServerAPI/node_modules/express/lib/router/index.js:335:12)
>    at next (/Library/WebServer/Documents/pantallas/pantallaServerAPI/node_modules/express/lib/router/index.js:275:10)
>    at /Library/WebServer/Documents/pantallas/pantallaServerAPI/node_modules/express/lib/router/index.js:635:15
>    at next (/Library/WebServer/Documents/pantallas/pantallaServerAPI/node_modules/express/lib/router/index.js:260:14)
>  path: '/Library/WebServer/Documents/pantallas/pantallaServerAPI/views/layouts/layout.ejs' }

I'm using:

sails 1.0.2
sails-pagination-middleware 0.0.2

**Comment by xtrinch** [comment]
Are you using any other middlewares? Because the error says variable 'me' is not defined. Where does that variable come from?

**Comment by crlsmtzprds** [comment]
Yes, I'm using just one a bodyParser to increase the size of uploaded files. bodyParser require skipper package but I don't understand why both middleware have conflict and where, why and what the variable "me" is.

This is my http.js

<pre style="margin: 0; line-height: 125%">module.exports.http <span style="color: #333333">=</span> {

    middleware<span style="color: #333333">:</span> {

        paginate<span style="color: #333333">:</span> require(<span style="background-color: #fff0f0">&#39;sails-pagination-middleware&#39;</span>),
        order<span style="color: #333333">:</span> [
            <span style="background-color: #fff0f0">&#39;paginate&#39;</span>,
            <span style="background-color: #fff0f0">&#39;bodyParser&#39;</span>
        ],

        bodyParser<span style="color: #333333">:</span> (<span style="color: #008800; font-weight: bold">function</span> _configureBodyParser() {
            <span style="color: #008800; font-weight: bold">var</span> skipper <span style="color: #333333">=</span> require(<span style="background-color: #fff0f0">&#39;skipper&#39;</span>);
            <span style="color: #008800; font-weight: bold">var</span> middlewareFn <span style="color: #333333">=</span> skipper({
                strict<span style="color: #333333">:</span> <span style="color: #008800; font-weight: bold">true</span>,
                limit<span style="color: #333333">:</span> <span style="background-color: #fff0f0">&#39;10mb&#39;</span>
            });
            <span style="color: #008800; font-weight: bold">return</span> middlewareFn;
        })(),

    }

};
</pre>

**Comment by xtrinch** [comment]
can you try putting paginate after body parser?

**Comment by crlsmtzprds** [comment]
Yes, I did it again right now and the same error appears, the pagination works but I can't access to files in assets folder
